// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgyitzqdyumrybhtdhsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhneWl0enFkeXVtcnliaHRkaHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODQ3MjQsImV4cCI6MjA2ODE2MDcyNH0.Z3uTdXERdouZ47wMFsm7zTt1jNSsthsZH9UX2AVopu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});